// Code generated by gowrap. DO NOT EDIT.
// template: ../../core/pkg/decorators/templates/czap_logger.template.go
// gowrap: http://github.com/hexdigest/gowrap

package decorator

//go:generate gowrap gen -p github.com/YFatMR/go_messenger/dialog_service/apientity -i DialogModel -t ../../core/pkg/decorators/templates/czap_logger.template.go -o dialog_model_czap_logger.gen.go -l ""

import (
	"context"

	"github.com/YFatMR/go_messenger/core/pkg/czap"
	"github.com/YFatMR/go_messenger/dialog_service/apientity"
	"github.com/YFatMR/go_messenger/dialog_service/entity"
	"go.uber.org/zap"
)

// LoggingDialogModelDecorator implements apientity.DialogModel that is instrumented with custom zap logger
type LoggingDialogModelDecorator struct {
	logger *czap.Logger
	base   apientity.DialogModel
}

// NewLoggingDialogModelDecorator instruments an implementation of the apientity.DialogModel with simple logging
func NewLoggingDialogModelDecorator(base apientity.DialogModel, logger *czap.Logger) *LoggingDialogModelDecorator {
	if base == nil {
		panic("LoggingDialogModelDecorator got empty base")
	}
	if logger == nil {
		panic("LoggingDialogModelDecorator got empty logger")
	}
	return &LoggingDialogModelDecorator{
		base:   base,
		logger: logger,
	}
}

// CreateDialog implements apientity.DialogModel
func (d *LoggingDialogModelDecorator) CreateDialog(ctx context.Context, userID1 *entity.UserID, userID2 *entity.UserID) (dialog *entity.Dialog, err error) {

	d.logger.InfoContext(ctx, "LoggingDialogModelDecorator: calling CreateDialog")
	defer func() {
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.InfoContext(ctx, "LoggingDialogModelDecorator: CreateDialog finished")
	}()
	return d.base.CreateDialog(ctx, userID1, userID2)
}

// GetDialogs implements apientity.DialogModel
func (d *LoggingDialogModelDecorator) GetDialogs(ctx context.Context, userID *entity.UserID, offset uint64, limit uint64) (dialogs []*entity.Dialog, err error) {

	d.logger.InfoContext(ctx, "LoggingDialogModelDecorator: calling GetDialogs")
	defer func() {
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.InfoContext(ctx, "LoggingDialogModelDecorator: GetDialogs finished")
	}()
	return d.base.GetDialogs(ctx, userID, offset, limit)
}
