// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: bots.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BotsServiceClient is the client API for BotsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BotsServiceClient interface {
	GetBotMessageCompletion(ctx context.Context, in *BotMessage, opts ...grpc.CallOption) (*BotMessage, error)
	Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error)
}

type botsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBotsServiceClient(cc grpc.ClientConnInterface) BotsServiceClient {
	return &botsServiceClient{cc}
}

func (c *botsServiceClient) GetBotMessageCompletion(ctx context.Context, in *BotMessage, opts ...grpc.CallOption) (*BotMessage, error) {
	out := new(BotMessage)
	err := c.cc.Invoke(ctx, "/proto.BotsService/GetBotMessageCompletion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botsServiceClient) Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/proto.BotsService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotsServiceServer is the server API for BotsService service.
// All implementations must embed UnimplementedBotsServiceServer
// for forward compatibility
type BotsServiceServer interface {
	GetBotMessageCompletion(context.Context, *BotMessage) (*BotMessage, error)
	Ping(context.Context, *Void) (*Pong, error)
	mustEmbedUnimplementedBotsServiceServer()
}

// UnimplementedBotsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBotsServiceServer struct {
}

func (UnimplementedBotsServiceServer) GetBotMessageCompletion(context.Context, *BotMessage) (*BotMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBotMessageCompletion not implemented")
}
func (UnimplementedBotsServiceServer) Ping(context.Context, *Void) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBotsServiceServer) mustEmbedUnimplementedBotsServiceServer() {}

// UnsafeBotsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotsServiceServer will
// result in compilation errors.
type UnsafeBotsServiceServer interface {
	mustEmbedUnimplementedBotsServiceServer()
}

func RegisterBotsServiceServer(s grpc.ServiceRegistrar, srv BotsServiceServer) {
	s.RegisterService(&BotsService_ServiceDesc, srv)
}

func _BotsService_GetBotMessageCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsServiceServer).GetBotMessageCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BotsService/GetBotMessageCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsServiceServer).GetBotMessageCompletion(ctx, req.(*BotMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BotsService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotsServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BotsService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotsServiceServer).Ping(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// BotsService_ServiceDesc is the grpc.ServiceDesc for BotsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BotsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BotsService",
	HandlerType: (*BotsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBotMessageCompletion",
			Handler:    _BotsService_GetBotMessageCompletion_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BotsService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bots.proto",
}
