// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: dialog.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DialogServiceClient is the client API for DialogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DialogServiceClient interface {
	CreateDialogWith(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Dialog, error)
	GetDialogByID(ctx context.Context, in *DialogID, opts ...grpc.CallOption) (*Dialog, error)
	GetDialogs(ctx context.Context, in *GetDialogsRequest, opts ...grpc.CallOption) (*GetDialogsResponse, error)
	CreateDialogMessage(ctx context.Context, in *CreateDialogMessageRequest, opts ...grpc.CallOption) (*CreateDialogMessageResponse, error)
	CreateDialogMessageWithCode(ctx context.Context, in *CreateDialogMessageWithCodeRequest, opts ...grpc.CallOption) (*CreateDialogMessageResponse, error)
	GetDialogMessages(ctx context.Context, in *GetDialogMessagesRequest, opts ...grpc.CallOption) (*GetDialogMessagesResponse, error)
	ReadMessage(ctx context.Context, in *ReadMessageRequest, opts ...grpc.CallOption) (*Void, error)
	CreateInstruction(ctx context.Context, in *CreateInstructionRequest, opts ...grpc.CallOption) (*InstructionID, error)
	GetInstructions(ctx context.Context, in *GetInstructionsRequest, opts ...grpc.CallOption) (*GetInstructionsResponse, error)
	GetInstructionsByID(ctx context.Context, in *GetInstructionsByIDRequest, opts ...grpc.CallOption) (*GetInstructionsResponse, error)
	GetDialogLinks(ctx context.Context, in *GetDialogLinksRequest, opts ...grpc.CallOption) (*GetDialogLinksResponse, error)
	GetDialogLinksByID(ctx context.Context, in *GetDialogLinksByIDRequest, opts ...grpc.CallOption) (*GetDialogLinksResponse, error)
	GetDialogMembers(ctx context.Context, in *DialogID, opts ...grpc.CallOption) (*GetDialogMembersResponse, error)
	GetUnreadDialogMessagesCount(ctx context.Context, in *DialogID, opts ...grpc.CallOption) (*GetUnreadDialogMessagesCountResponse, error)
	Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error)
}

type dialogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDialogServiceClient(cc grpc.ClientConnInterface) DialogServiceClient {
	return &dialogServiceClient{cc}
}

func (c *dialogServiceClient) CreateDialogWith(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*Dialog, error) {
	out := new(Dialog)
	err := c.cc.Invoke(ctx, "/proto.DialogService/CreateDialogWith", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetDialogByID(ctx context.Context, in *DialogID, opts ...grpc.CallOption) (*Dialog, error) {
	out := new(Dialog)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetDialogByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetDialogs(ctx context.Context, in *GetDialogsRequest, opts ...grpc.CallOption) (*GetDialogsResponse, error) {
	out := new(GetDialogsResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetDialogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) CreateDialogMessage(ctx context.Context, in *CreateDialogMessageRequest, opts ...grpc.CallOption) (*CreateDialogMessageResponse, error) {
	out := new(CreateDialogMessageResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/CreateDialogMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) CreateDialogMessageWithCode(ctx context.Context, in *CreateDialogMessageWithCodeRequest, opts ...grpc.CallOption) (*CreateDialogMessageResponse, error) {
	out := new(CreateDialogMessageResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/CreateDialogMessageWithCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetDialogMessages(ctx context.Context, in *GetDialogMessagesRequest, opts ...grpc.CallOption) (*GetDialogMessagesResponse, error) {
	out := new(GetDialogMessagesResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetDialogMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) ReadMessage(ctx context.Context, in *ReadMessageRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/proto.DialogService/ReadMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) CreateInstruction(ctx context.Context, in *CreateInstructionRequest, opts ...grpc.CallOption) (*InstructionID, error) {
	out := new(InstructionID)
	err := c.cc.Invoke(ctx, "/proto.DialogService/CreateInstruction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetInstructions(ctx context.Context, in *GetInstructionsRequest, opts ...grpc.CallOption) (*GetInstructionsResponse, error) {
	out := new(GetInstructionsResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetInstructions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetInstructionsByID(ctx context.Context, in *GetInstructionsByIDRequest, opts ...grpc.CallOption) (*GetInstructionsResponse, error) {
	out := new(GetInstructionsResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetInstructionsByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetDialogLinks(ctx context.Context, in *GetDialogLinksRequest, opts ...grpc.CallOption) (*GetDialogLinksResponse, error) {
	out := new(GetDialogLinksResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetDialogLinks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetDialogLinksByID(ctx context.Context, in *GetDialogLinksByIDRequest, opts ...grpc.CallOption) (*GetDialogLinksResponse, error) {
	out := new(GetDialogLinksResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetDialogLinksByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetDialogMembers(ctx context.Context, in *DialogID, opts ...grpc.CallOption) (*GetDialogMembersResponse, error) {
	out := new(GetDialogMembersResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetDialogMembers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) GetUnreadDialogMessagesCount(ctx context.Context, in *DialogID, opts ...grpc.CallOption) (*GetUnreadDialogMessagesCountResponse, error) {
	out := new(GetUnreadDialogMessagesCountResponse)
	err := c.cc.Invoke(ctx, "/proto.DialogService/GetUnreadDialogMessagesCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dialogServiceClient) Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/proto.DialogService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DialogServiceServer is the server API for DialogService service.
// All implementations must embed UnimplementedDialogServiceServer
// for forward compatibility
type DialogServiceServer interface {
	CreateDialogWith(context.Context, *UserID) (*Dialog, error)
	GetDialogByID(context.Context, *DialogID) (*Dialog, error)
	GetDialogs(context.Context, *GetDialogsRequest) (*GetDialogsResponse, error)
	CreateDialogMessage(context.Context, *CreateDialogMessageRequest) (*CreateDialogMessageResponse, error)
	CreateDialogMessageWithCode(context.Context, *CreateDialogMessageWithCodeRequest) (*CreateDialogMessageResponse, error)
	GetDialogMessages(context.Context, *GetDialogMessagesRequest) (*GetDialogMessagesResponse, error)
	ReadMessage(context.Context, *ReadMessageRequest) (*Void, error)
	CreateInstruction(context.Context, *CreateInstructionRequest) (*InstructionID, error)
	GetInstructions(context.Context, *GetInstructionsRequest) (*GetInstructionsResponse, error)
	GetInstructionsByID(context.Context, *GetInstructionsByIDRequest) (*GetInstructionsResponse, error)
	GetDialogLinks(context.Context, *GetDialogLinksRequest) (*GetDialogLinksResponse, error)
	GetDialogLinksByID(context.Context, *GetDialogLinksByIDRequest) (*GetDialogLinksResponse, error)
	GetDialogMembers(context.Context, *DialogID) (*GetDialogMembersResponse, error)
	GetUnreadDialogMessagesCount(context.Context, *DialogID) (*GetUnreadDialogMessagesCountResponse, error)
	Ping(context.Context, *Void) (*Pong, error)
	mustEmbedUnimplementedDialogServiceServer()
}

// UnimplementedDialogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDialogServiceServer struct {
}

func (UnimplementedDialogServiceServer) CreateDialogWith(context.Context, *UserID) (*Dialog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDialogWith not implemented")
}
func (UnimplementedDialogServiceServer) GetDialogByID(context.Context, *DialogID) (*Dialog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogByID not implemented")
}
func (UnimplementedDialogServiceServer) GetDialogs(context.Context, *GetDialogsRequest) (*GetDialogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogs not implemented")
}
func (UnimplementedDialogServiceServer) CreateDialogMessage(context.Context, *CreateDialogMessageRequest) (*CreateDialogMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDialogMessage not implemented")
}
func (UnimplementedDialogServiceServer) CreateDialogMessageWithCode(context.Context, *CreateDialogMessageWithCodeRequest) (*CreateDialogMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDialogMessageWithCode not implemented")
}
func (UnimplementedDialogServiceServer) GetDialogMessages(context.Context, *GetDialogMessagesRequest) (*GetDialogMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogMessages not implemented")
}
func (UnimplementedDialogServiceServer) ReadMessage(context.Context, *ReadMessageRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMessage not implemented")
}
func (UnimplementedDialogServiceServer) CreateInstruction(context.Context, *CreateInstructionRequest) (*InstructionID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstruction not implemented")
}
func (UnimplementedDialogServiceServer) GetInstructions(context.Context, *GetInstructionsRequest) (*GetInstructionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstructions not implemented")
}
func (UnimplementedDialogServiceServer) GetInstructionsByID(context.Context, *GetInstructionsByIDRequest) (*GetInstructionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstructionsByID not implemented")
}
func (UnimplementedDialogServiceServer) GetDialogLinks(context.Context, *GetDialogLinksRequest) (*GetDialogLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogLinks not implemented")
}
func (UnimplementedDialogServiceServer) GetDialogLinksByID(context.Context, *GetDialogLinksByIDRequest) (*GetDialogLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogLinksByID not implemented")
}
func (UnimplementedDialogServiceServer) GetDialogMembers(context.Context, *DialogID) (*GetDialogMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogMembers not implemented")
}
func (UnimplementedDialogServiceServer) GetUnreadDialogMessagesCount(context.Context, *DialogID) (*GetUnreadDialogMessagesCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadDialogMessagesCount not implemented")
}
func (UnimplementedDialogServiceServer) Ping(context.Context, *Void) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDialogServiceServer) mustEmbedUnimplementedDialogServiceServer() {}

// UnsafeDialogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DialogServiceServer will
// result in compilation errors.
type UnsafeDialogServiceServer interface {
	mustEmbedUnimplementedDialogServiceServer()
}

func RegisterDialogServiceServer(s grpc.ServiceRegistrar, srv DialogServiceServer) {
	s.RegisterService(&DialogService_ServiceDesc, srv)
}

func _DialogService_CreateDialogWith_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).CreateDialogWith(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/CreateDialogWith",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).CreateDialogWith(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetDialogByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialogID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetDialogByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetDialogByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetDialogByID(ctx, req.(*DialogID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetDialogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDialogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetDialogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetDialogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetDialogs(ctx, req.(*GetDialogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_CreateDialogMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDialogMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).CreateDialogMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/CreateDialogMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).CreateDialogMessage(ctx, req.(*CreateDialogMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_CreateDialogMessageWithCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDialogMessageWithCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).CreateDialogMessageWithCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/CreateDialogMessageWithCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).CreateDialogMessageWithCode(ctx, req.(*CreateDialogMessageWithCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetDialogMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDialogMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetDialogMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetDialogMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetDialogMessages(ctx, req.(*GetDialogMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_ReadMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).ReadMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/ReadMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).ReadMessage(ctx, req.(*ReadMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_CreateInstruction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstructionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).CreateInstruction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/CreateInstruction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).CreateInstruction(ctx, req.(*CreateInstructionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetInstructions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstructionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetInstructions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetInstructions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetInstructions(ctx, req.(*GetInstructionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetInstructionsByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstructionsByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetInstructionsByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetInstructionsByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetInstructionsByID(ctx, req.(*GetInstructionsByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetDialogLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDialogLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetDialogLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetDialogLinks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetDialogLinks(ctx, req.(*GetDialogLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetDialogLinksByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDialogLinksByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetDialogLinksByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetDialogLinksByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetDialogLinksByID(ctx, req.(*GetDialogLinksByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetDialogMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialogID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetDialogMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetDialogMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetDialogMembers(ctx, req.(*DialogID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_GetUnreadDialogMessagesCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DialogID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).GetUnreadDialogMessagesCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/GetUnreadDialogMessagesCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).GetUnreadDialogMessagesCount(ctx, req.(*DialogID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DialogService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DialogServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DialogService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DialogServiceServer).Ping(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// DialogService_ServiceDesc is the grpc.ServiceDesc for DialogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DialogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DialogService",
	HandlerType: (*DialogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDialogWith",
			Handler:    _DialogService_CreateDialogWith_Handler,
		},
		{
			MethodName: "GetDialogByID",
			Handler:    _DialogService_GetDialogByID_Handler,
		},
		{
			MethodName: "GetDialogs",
			Handler:    _DialogService_GetDialogs_Handler,
		},
		{
			MethodName: "CreateDialogMessage",
			Handler:    _DialogService_CreateDialogMessage_Handler,
		},
		{
			MethodName: "CreateDialogMessageWithCode",
			Handler:    _DialogService_CreateDialogMessageWithCode_Handler,
		},
		{
			MethodName: "GetDialogMessages",
			Handler:    _DialogService_GetDialogMessages_Handler,
		},
		{
			MethodName: "ReadMessage",
			Handler:    _DialogService_ReadMessage_Handler,
		},
		{
			MethodName: "CreateInstruction",
			Handler:    _DialogService_CreateInstruction_Handler,
		},
		{
			MethodName: "GetInstructions",
			Handler:    _DialogService_GetInstructions_Handler,
		},
		{
			MethodName: "GetInstructionsByID",
			Handler:    _DialogService_GetInstructionsByID_Handler,
		},
		{
			MethodName: "GetDialogLinks",
			Handler:    _DialogService_GetDialogLinks_Handler,
		},
		{
			MethodName: "GetDialogLinksByID",
			Handler:    _DialogService_GetDialogLinksByID_Handler,
		},
		{
			MethodName: "GetDialogMembers",
			Handler:    _DialogService_GetDialogMembers_Handler,
		},
		{
			MethodName: "GetUnreadDialogMessagesCount",
			Handler:    _DialogService_GetUnreadDialogMessagesCount_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _DialogService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dialog.proto",
}
