// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: front.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FrontClient is the client API for Front service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserID, error)
	GenerateToken(ctx context.Context, in *Credential, opts ...grpc.CallOption) (*Token, error)
	GetUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserData, error)
	GetProgramByID(ctx context.Context, in *ProgramID, opts ...grpc.CallOption) (*Program, error)
	CreateProgram(ctx context.Context, in *ProgramSource, opts ...grpc.CallOption) (*ProgramID, error)
	UpdateProgramSource(ctx context.Context, in *UpdateProgramSourceRequest, opts ...grpc.CallOption) (*Void, error)
	RunProgram(ctx context.Context, in *ProgramID, opts ...grpc.CallOption) (*Void, error)
	LintProgram(ctx context.Context, in *ProgramID, opts ...grpc.CallOption) (*Void, error)
	Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error)
}

type frontClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontClient(cc grpc.ClientConnInterface) FrontClient {
	return &frontClient{cc}
}

func (c *frontClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserID, error) {
	out := new(UserID)
	err := c.cc.Invoke(ctx, "/proto.Front/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontClient) GenerateToken(ctx context.Context, in *Credential, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/proto.Front/GenerateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontClient) GetUserByID(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*UserData, error) {
	out := new(UserData)
	err := c.cc.Invoke(ctx, "/proto.Front/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontClient) GetProgramByID(ctx context.Context, in *ProgramID, opts ...grpc.CallOption) (*Program, error) {
	out := new(Program)
	err := c.cc.Invoke(ctx, "/proto.Front/GetProgramByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontClient) CreateProgram(ctx context.Context, in *ProgramSource, opts ...grpc.CallOption) (*ProgramID, error) {
	out := new(ProgramID)
	err := c.cc.Invoke(ctx, "/proto.Front/CreateProgram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontClient) UpdateProgramSource(ctx context.Context, in *UpdateProgramSourceRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/proto.Front/UpdateProgramSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontClient) RunProgram(ctx context.Context, in *ProgramID, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/proto.Front/RunProgram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontClient) LintProgram(ctx context.Context, in *ProgramID, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/proto.Front/LintProgram", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontClient) Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/proto.Front/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontServer is the server API for Front service.
// All implementations must embed UnimplementedFrontServer
// for forward compatibility
type FrontServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*UserID, error)
	GenerateToken(context.Context, *Credential) (*Token, error)
	GetUserByID(context.Context, *UserID) (*UserData, error)
	GetProgramByID(context.Context, *ProgramID) (*Program, error)
	CreateProgram(context.Context, *ProgramSource) (*ProgramID, error)
	UpdateProgramSource(context.Context, *UpdateProgramSourceRequest) (*Void, error)
	RunProgram(context.Context, *ProgramID) (*Void, error)
	LintProgram(context.Context, *ProgramID) (*Void, error)
	Ping(context.Context, *Void) (*Pong, error)
	mustEmbedUnimplementedFrontServer()
}

// UnimplementedFrontServer must be embedded to have forward compatible implementations.
type UnimplementedFrontServer struct {
}

func (UnimplementedFrontServer) CreateUser(context.Context, *CreateUserRequest) (*UserID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedFrontServer) GenerateToken(context.Context, *Credential) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (UnimplementedFrontServer) GetUserByID(context.Context, *UserID) (*UserData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (UnimplementedFrontServer) GetProgramByID(context.Context, *ProgramID) (*Program, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProgramByID not implemented")
}
func (UnimplementedFrontServer) CreateProgram(context.Context, *ProgramSource) (*ProgramID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProgram not implemented")
}
func (UnimplementedFrontServer) UpdateProgramSource(context.Context, *UpdateProgramSourceRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProgramSource not implemented")
}
func (UnimplementedFrontServer) RunProgram(context.Context, *ProgramID) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunProgram not implemented")
}
func (UnimplementedFrontServer) LintProgram(context.Context, *ProgramID) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LintProgram not implemented")
}
func (UnimplementedFrontServer) Ping(context.Context, *Void) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFrontServer) mustEmbedUnimplementedFrontServer() {}

// UnsafeFrontServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontServer will
// result in compilation errors.
type UnsafeFrontServer interface {
	mustEmbedUnimplementedFrontServer()
}

func RegisterFrontServer(s grpc.ServiceRegistrar, srv FrontServer) {
	s.RegisterService(&Front_ServiceDesc, srv)
}

func _Front_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Front_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credential)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/GenerateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).GenerateToken(ctx, req.(*Credential))
	}
	return interceptor(ctx, in, info, handler)
}

func _Front_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).GetUserByID(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Front_GetProgramByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).GetProgramByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/GetProgramByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).GetProgramByID(ctx, req.(*ProgramID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Front_CreateProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramSource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).CreateProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/CreateProgram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).CreateProgram(ctx, req.(*ProgramSource))
	}
	return interceptor(ctx, in, info, handler)
}

func _Front_UpdateProgramSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgramSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).UpdateProgramSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/UpdateProgramSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).UpdateProgramSource(ctx, req.(*UpdateProgramSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Front_RunProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).RunProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/RunProgram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).RunProgram(ctx, req.(*ProgramID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Front_LintProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).LintProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/LintProgram",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).LintProgram(ctx, req.(*ProgramID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Front_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Front/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontServer).Ping(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// Front_ServiceDesc is the grpc.ServiceDesc for Front service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Front_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Front",
	HandlerType: (*FrontServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Front_CreateUser_Handler,
		},
		{
			MethodName: "GenerateToken",
			Handler:    _Front_GenerateToken_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _Front_GetUserByID_Handler,
		},
		{
			MethodName: "GetProgramByID",
			Handler:    _Front_GetProgramByID_Handler,
		},
		{
			MethodName: "CreateProgram",
			Handler:    _Front_CreateProgram_Handler,
		},
		{
			MethodName: "UpdateProgramSource",
			Handler:    _Front_UpdateProgramSource_Handler,
		},
		{
			MethodName: "RunProgram",
			Handler:    _Front_RunProgram_Handler,
		},
		{
			MethodName: "LintProgram",
			Handler:    _Front_LintProgram_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Front_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "front.proto",
}
