// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserData struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserData) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

type Credential struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Credential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credential.Unmarshal(m, b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
}
func (m *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(m, src)
}
func (m *Credential) XXX_Size() int {
	return xxx_messageInfo_Credential.Size(m)
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Credential) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Credential) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type Token struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type UserID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CreateUserRequest struct {
	Credential           *Credential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	UserData             *UserData   `protobuf:"bytes,2,opt,name=userData,proto3" json:"userData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetCredential() *Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *CreateUserRequest) GetUserData() *UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

func init() {
	proto.RegisterType((*UserData)(nil), "proto.UserData")
	proto.RegisterType((*Credential)(nil), "proto.Credential")
	proto.RegisterType((*Token)(nil), "proto.Token")
	proto.RegisterType((*UserID)(nil), "proto.UserID")
	proto.RegisterType((*CreateUserRequest)(nil), "proto.CreateUserRequest")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x6f, 0xe2, 0x30,
	0x10, 0xc5, 0x03, 0xcb, 0xdf, 0x09, 0xb0, 0x62, 0xb4, 0x87, 0x28, 0x27, 0xe4, 0xd3, 0xae, 0x56,
	0x0a, 0x6a, 0x7a, 0xe8, 0x1d, 0x22, 0xa1, 0xdc, 0x50, 0x44, 0x7b, 0xe8, 0xcd, 0x0d, 0x23, 0x14,
	0x11, 0x6c, 0x6a, 0x27, 0xaa, 0xfa, 0xcd, 0x7b, 0xac, 0xe2, 0x98, 0x10, 0xda, 0x9e, 0xec, 0xf7,
	0xf3, 0xf8, 0xcd, 0xcc, 0x03, 0x28, 0x35, 0xa9, 0xe0, 0xac, 0x64, 0x21, 0xb1, 0x6f, 0x0e, 0x7f,
	0x92, 0xca, 0xd3, 0x49, 0x8a, 0x1a, 0xb2, 0x1d, 0x8c, 0x1e, 0x35, 0xa9, 0x88, 0x17, 0x1c, 0x7d,
	0x18, 0x89, 0x2c, 0x3d, 0x0a, 0x7e, 0x22, 0xaf, 0xb3, 0xe8, 0xfc, 0x1d, 0x27, 0x8d, 0x46, 0x84,
	0x9e, 0xe1, 0x5d, 0xc3, 0xcd, 0x1d, 0x3d, 0x18, 0xea, 0x52, 0x19, 0xfc, 0xcb, 0xe0, 0x8b, 0x64,
	0x09, 0xc0, 0x5a, 0xd1, 0x9e, 0x44, 0x91, 0xf1, 0x1c, 0xff, 0x40, 0x3f, 0x97, 0x87, 0x4c, 0x58,
	0xd3, 0x5a, 0x54, 0xdd, 0xce, 0x5c, 0xeb, 0x37, 0xa9, 0xf6, 0xd6, 0xb5, 0xd1, 0x55, 0x37, 0x25,
	0xf3, 0x8b, 0xad, 0xb9, 0xb3, 0x7f, 0xd0, 0xdf, 0xc9, 0x23, 0x09, 0x5c, 0x80, 0xcb, 0xd3, 0x94,
	0xb4, 0x36, 0xd2, 0x9a, 0xb6, 0x11, 0xf3, 0x60, 0x50, 0x2d, 0x15, 0x47, 0x38, 0x83, 0x6e, 0x1c,
	0xd9, 0x92, 0x6e, 0x1c, 0x31, 0x0d, 0xf3, 0xb5, 0x22, 0x5e, 0x50, 0xf5, 0x9e, 0xd0, 0x6b, 0x49,
	0xba, 0xc0, 0x3b, 0x80, 0xb4, 0x99, 0xd6, 0x14, 0xbb, 0xe1, 0xbc, 0xce, 0x27, 0xb8, 0xae, 0x91,
	0xb4, 0x8a, 0xf0, 0x3f, 0x8c, 0x4a, 0x1b, 0x9b, 0x19, 0xde, 0x0d, 0x7f, 0xdb, 0x0f, 0x97, 0x34,
	0x93, 0xa6, 0x20, 0xfc, 0xe8, 0x40, 0xaf, 0xc2, 0xf8, 0x60, 0x62, 0xb1, 0xdd, 0xd1, 0xbb, 0xb6,
	0xb8, 0x1d, 0xc8, 0x9f, 0xb6, 0xbc, 0xe2, 0x88, 0x39, 0xb8, 0x04, 0x77, 0x43, 0x45, 0x25, 0x57,
	0xef, 0x71, 0x84, 0xb7, 0xef, 0xfe, 0xd7, 0xd6, 0xcc, 0xc1, 0x00, 0x66, 0x11, 0xe5, 0x54, 0xdb,
	0xfe, 0xf4, 0xc7, 0xb5, 0xf2, 0x49, 0x66, 0x7b, 0xe6, 0x60, 0x08, 0xd3, 0x0d, 0x09, 0x52, 0xbc,
	0xa0, 0x3a, 0xe4, 0xef, 0xfb, 0xfb, 0x13, 0x8b, 0xea, 0x8c, 0x1d, 0x64, 0xd0, 0xdb, 0x66, 0xe2,
	0x80, 0x6d, 0xab, 0xc6, 0x77, 0x2b, 0xc5, 0x81, 0x39, 0xab, 0xf1, 0xf3, 0x30, 0x58, 0x1a, 0xf2,
	0x32, 0x30, 0xc7, 0xfd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xaa, 0x0c, 0xd7, 0x93, 0x02,
	0x00, 0x00,
}
