// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserData) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

type UserID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CreateUserDataRequest struct {
	AccountID            *AccountID `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	UserData             *UserData  `protobuf:"bytes,2,opt,name=userData,proto3" json:"userData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateUserDataRequest) Reset()         { *m = CreateUserDataRequest{} }
func (m *CreateUserDataRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserDataRequest) ProtoMessage()    {}
func (*CreateUserDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserDataRequest.Unmarshal(m, b)
}
func (m *CreateUserDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserDataRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserDataRequest.Merge(m, src)
}
func (m *CreateUserDataRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserDataRequest.Size(m)
}
func (m *CreateUserDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserDataRequest proto.InternalMessageInfo

func (m *CreateUserDataRequest) GetAccountID() *AccountID {
	if m != nil {
		return m.AccountID
	}
	return nil
}

func (m *CreateUserDataRequest) GetUserData() *UserData {
	if m != nil {
		return m.UserData
	}
	return nil
}

func init() {
	proto.RegisterType((*UserData)(nil), "proto.UserData")
	proto.RegisterType((*UserID)(nil), "proto.UserID")
	proto.RegisterType((*CreateUserDataRequest)(nil), "proto.CreateUserDataRequest")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd3, 0x10, 0xdb, 0x66, 0xa2, 0x55, 0x06, 0x84, 0x10, 0x3c, 0xc8, 0x9e, 0x04, 0x21,
	0x85, 0x78, 0x11, 0x3c, 0x59, 0x17, 0x24, 0xb7, 0x12, 0xd0, 0x83, 0xb7, 0x35, 0x0e, 0xb5, 0x60,
	0x76, 0x75, 0xb3, 0x7b, 0xf0, 0x1f, 0xfa, 0xb3, 0x24, 0x9b, 0x4d, 0x5a, 0xa5, 0xa7, 0xd9, 0xf7,
	0xed, 0x7b, 0x6f, 0x06, 0xc0, 0xb6, 0xa4, 0xf3, 0x4f, 0xad, 0x8c, 0xc2, 0x23, 0x37, 0x32, 0x10,
	0xd6, 0xbc, 0xf7, 0x28, 0x3b, 0xae, 0x55, 0xd3, 0x28, 0xd9, 0x2b, 0x76, 0x0b, 0xf3, 0xa7, 0x96,
	0x34, 0x17, 0x46, 0x20, 0x42, 0x24, 0x45, 0x43, 0xe9, 0xe4, 0x72, 0x72, 0x15, 0x57, 0xee, 0x8d,
	0x29, 0xcc, 0x5a, 0xab, 0x1d, 0x0e, 0x1d, 0x1e, 0x24, 0x4b, 0x61, 0xda, 0x25, 0x4b, 0x8e, 0x0b,
	0x08, 0x4b, 0xee, 0x53, 0x61, 0xc9, 0x99, 0x81, 0xf3, 0x07, 0x4d, 0xc2, 0xd0, 0xd0, 0x5c, 0xd1,
	0x97, 0xa5, 0xd6, 0x60, 0x0e, 0xb1, 0xa8, 0x6b, 0x65, 0xa5, 0xf1, 0xfe, 0xa4, 0x38, 0xeb, 0xef,
	0xc8, 0xef, 0x07, 0x5e, 0xed, 0x2c, 0x78, 0x0d, 0x73, 0xeb, 0x2b, 0xdc, 0xf6, 0xa4, 0x38, 0xf5,
	0xf6, 0xb1, 0x79, 0x34, 0x14, 0x3f, 0x13, 0x88, 0x3a, 0x8c, 0x77, 0x00, 0xbb, 0xf5, 0x78, 0xe1,
	0x13, 0x07, 0x2f, 0xca, 0x4e, 0xf6, 0xfa, 0x4a, 0xce, 0x02, 0x5c, 0x42, 0xf2, 0x48, 0xa6, 0x93,
	0xab, 0xef, 0x92, 0xe3, 0xdf, 0xff, 0xec, 0xff, 0x7a, 0x16, 0x60, 0x0e, 0x0b, 0x4e, 0x1f, 0xd4,
	0x57, 0x1f, 0xca, 0x24, 0x5e, 0x3e, 0xab, 0xed, 0x1b, 0x0b, 0x90, 0x41, 0xb4, 0xde, 0xca, 0x0d,
	0xee, 0xe3, 0xd1, 0xb3, 0x56, 0x72, 0xc3, 0x82, 0x55, 0xfc, 0x32, 0xcb, 0x97, 0x8e, 0xbc, 0x4e,
	0xdd, 0xb8, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xf2, 0x06, 0x11, 0xd5, 0x01, 0x00, 0x00,
}
