// Code generated by gowrap. DO NOT EDIT.
// template: ../../core/pkg/decorators/templates/czap_logger.template.go
// gowrap: http://github.com/hexdigest/gowrap

package decorator

//go:generate gowrap gen -p github.com/YFatMR/go_messenger/user_service/apientity -i UserService -t ../../core/pkg/decorators/templates/czap_logger.template.go -o user_service_czap_logger.gen.go -l ""

import (
	"context"

	"github.com/YFatMR/go_messenger/core/pkg/czap"
	"github.com/YFatMR/go_messenger/user_service/apientity"
	"github.com/YFatMR/go_messenger/user_service/entity"
	"go.uber.org/zap"
)

// LoggingUserServiceDecorator implements apientity.UserService that is instrumented with custom zap logger
type LoggingUserServiceDecorator struct {
	logger *czap.Logger
	base   apientity.UserService
}

// NewLoggingUserServiceDecorator instruments an implementation of the apientity.UserService with simple logging
func NewLoggingUserServiceDecorator(base apientity.UserService, logger *czap.Logger) *LoggingUserServiceDecorator {
	if base == nil {
		panic("LoggingUserServiceDecorator got empty base")
	}
	if logger == nil {
		panic("LoggingUserServiceDecorator got empty logger")
	}
	return &LoggingUserServiceDecorator{
		base:   base,
		logger: logger,
	}
}

// Create implements apientity.UserService
func (d *LoggingUserServiceDecorator) Create(ctx context.Context, user *entity.User, unsafeCredential *entity.UnsafeCredential) (userID *entity.UserID, err error) {

	d.logger.InfoContext(ctx, "LoggingUserServiceDecorator: calling Create")
	defer func() {
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.InfoContext(ctx, "LoggingUserServiceDecorator: Create finished")
	}()
	return d.base.Create(ctx, user, unsafeCredential)
}

// DeleteByID implements apientity.UserService
func (d *LoggingUserServiceDecorator) DeleteByID(ctx context.Context, userID *entity.UserID) (err error) {

	d.logger.InfoContext(ctx, "LoggingUserServiceDecorator: calling DeleteByID")
	defer func() {
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.InfoContext(ctx, "LoggingUserServiceDecorator: DeleteByID finished")
	}()
	return d.base.DeleteByID(ctx, userID)
}

// GenerateToken implements apientity.UserService
func (d *LoggingUserServiceDecorator) GenerateToken(ctx context.Context, unsafeCredential *entity.UnsafeCredential) (token *entity.Token, err error) {

	d.logger.InfoContext(ctx, "LoggingUserServiceDecorator: calling GenerateToken")
	defer func() {
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.InfoContext(ctx, "LoggingUserServiceDecorator: GenerateToken finished")
	}()
	return d.base.GenerateToken(ctx, unsafeCredential)
}

// GetByID implements apientity.UserService
func (d *LoggingUserServiceDecorator) GetByID(ctx context.Context, userID *entity.UserID) (user *entity.User, err error) {

	d.logger.InfoContext(ctx, "LoggingUserServiceDecorator: calling GetByID")
	defer func() {
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.InfoContext(ctx, "LoggingUserServiceDecorator: GetByID finished")
	}()
	return d.base.GetByID(ctx, userID)
}
