// Code generated by gowrap. DO NOT EDIT.
// template: ../../core/pkg/decorators/templates/prometheus_metrics.template.go
// gowrap: http://github.com/hexdigest/gowrap

package decorator

//go:generate gowrap gen -p github.com/YFatMR/go_messenger/user_service/apientity -i UserRepository -t ../../core/pkg/decorators/templates/prometheus_metrics.template.go -o user_repository_prometheus_metrics.gen.go -v metricPrefix=database_query -v globalVarPrefix=private_UserRepository_ -l ""

import (
	"context"
	"time"

	"github.com/YFatMR/go_messenger/user_service/apientity"
	"github.com/YFatMR/go_messenger/user_service/entity"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

const (
	private_UserRepository_okStatusTag    = "ok"
	private_UserRepository_errorStatusTag = "error"
)

// Prefixes:
// database_query: for database
// service_request: for seervices

// Naming rule: https://prometheus.io/docs/practices/naming/
var (
	private_UserRepository_DurationSeconds = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "database_query_duration_seconds",
		Buckets: []float64{0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 4},
		Help:    "Duration of one database query",
	}, []string{"status", "operation"})
	private_UserRepository_ProcessedTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "database_query_processed_total",
		Help: "Count of query to database",
	}, []string{"status", "operation"})
	private_UserRepository_StartProcessTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "database_query_start_process_total",
		Help: "Count of started queries",
	})
)

// PrometheusMetricsUserRepositoryDecorator implements apientity.UserRepository that is instrumented with custom zap logger
type PrometheusMetricsUserRepositoryDecorator struct {
	base apientity.UserRepository
}

// NewPrometheusMetricsUserRepositoryDecorator instruments an implementation of the apientity.UserRepository with simple logging
func NewPrometheusMetricsUserRepositoryDecorator(base apientity.UserRepository) *PrometheusMetricsUserRepositoryDecorator {
	if base == nil {
		panic("PrometheusMetricsUserRepositoryDecorator got empty base")
	}
	return &PrometheusMetricsUserRepositoryDecorator{
		base: base,
	}
}

// Create implements apientity.UserRepository
func (d *PrometheusMetricsUserRepositoryDecorator) Create(ctx context.Context, user *entity.User, credential *entity.Credential) (userID *entity.UserID, err error) {

	startTime := time.Now()
	private_UserRepository_StartProcessTotal.Inc()
	defer func() {
		functionDuration := time.Since(startTime).Seconds()
		statusTag := private_UserRepository_okStatusTag

		if err != nil {
			statusTag = private_UserRepository_errorStatusTag
		}

		private_UserRepository_DurationSeconds.WithLabelValues(statusTag, "create").Observe(functionDuration)
		private_UserRepository_ProcessedTotal.WithLabelValues(statusTag, "create").Inc()
	}()
	return d.base.Create(ctx, user, credential)
}

// DeleteByID implements apientity.UserRepository
func (d *PrometheusMetricsUserRepositoryDecorator) DeleteByID(ctx context.Context, userID *entity.UserID) (err error) {

	startTime := time.Now()
	private_UserRepository_StartProcessTotal.Inc()
	defer func() {
		functionDuration := time.Since(startTime).Seconds()
		statusTag := private_UserRepository_okStatusTag

		if err != nil {
			statusTag = private_UserRepository_errorStatusTag
		}

		private_UserRepository_DurationSeconds.WithLabelValues(statusTag, "delete_by_id").Observe(functionDuration)
		private_UserRepository_ProcessedTotal.WithLabelValues(statusTag, "delete_by_id").Inc()
	}()
	return d.base.DeleteByID(ctx, userID)
}

// GetAccountByEmail implements apientity.UserRepository
func (d *PrometheusMetricsUserRepositoryDecorator) GetAccountByEmail(ctx context.Context, email string) (account *entity.Account, err error) {

	startTime := time.Now()
	private_UserRepository_StartProcessTotal.Inc()
	defer func() {
		functionDuration := time.Since(startTime).Seconds()
		statusTag := private_UserRepository_okStatusTag

		if err != nil {
			statusTag = private_UserRepository_errorStatusTag
		}

		private_UserRepository_DurationSeconds.WithLabelValues(statusTag, "get_account_by_email").Observe(functionDuration)
		private_UserRepository_ProcessedTotal.WithLabelValues(statusTag, "get_account_by_email").Inc()
	}()
	return d.base.GetAccountByEmail(ctx, email)
}

// GetByID implements apientity.UserRepository
func (d *PrometheusMetricsUserRepositoryDecorator) GetByID(ctx context.Context, userID *entity.UserID) (user *entity.User, err error) {

	startTime := time.Now()
	private_UserRepository_StartProcessTotal.Inc()
	defer func() {
		functionDuration := time.Since(startTime).Seconds()
		statusTag := private_UserRepository_okStatusTag

		if err != nil {
			statusTag = private_UserRepository_errorStatusTag
		}

		private_UserRepository_DurationSeconds.WithLabelValues(statusTag, "get_by_id").Observe(functionDuration)
		private_UserRepository_ProcessedTotal.WithLabelValues(statusTag, "get_by_id").Inc()
	}()
	return d.base.GetByID(ctx, userID)
}
