// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../core/pkg/decorators/templates/opentelemetry_tracing.go
// gowrap: http://github.com/hexdigest/gowrap

package decorators

//go:generate gowrap gen -p github.com/YFatMR/go_messenger/auth_service/internal/repositories -i AccountRepository -t ../../../../core/pkg/decorators/templates/opentelemetry_tracing.go -o opentelemetry_tracing.gen.go -l ""

import (
	"context"

	"github.com/YFatMR/go_messenger/auth_service/internal/entities"
	"github.com/YFatMR/go_messenger/auth_service/internal/entities/accountid"
	"github.com/YFatMR/go_messenger/auth_service/internal/entities/credential"
	"github.com/YFatMR/go_messenger/auth_service/internal/entities/tokenpayload"
	"github.com/YFatMR/go_messenger/auth_service/internal/repositories"
	"github.com/YFatMR/go_messenger/core/pkg/errors/logerr"
	"go.opentelemetry.io/otel/trace"
)

// OpentelemetryTracingAccountRepositoryDecorator implements repositories.AccountRepository that is instrumented with custom zap logger
type OpentelemetryTracingAccountRepositoryDecorator struct {
	base         repositories.AccountRepository
	tracer       trace.Tracer
	recordErrors bool
}

// NewOpentelemetryTracingAccountRepositoryDecorator instruments an implementation of the repositories.AccountRepository with simple logging
func NewOpentelemetryTracingAccountRepositoryDecorator(base repositories.AccountRepository, tracer trace.Tracer, recordErrors bool) *OpentelemetryTracingAccountRepositoryDecorator {
	if base == nil {
		panic("OpentelemetryTracingAccountRepositoryDecorator got empty base")
	}
	if tracer == nil {
		panic("OpentelemetryTracingAccountRepositoryDecorator got empty tracer")
	}
	return &OpentelemetryTracingAccountRepositoryDecorator{
		base:         base,
		tracer:       tracer,
		recordErrors: recordErrors,
	}
}

// CreateAccount implements repositories.AccountRepository
func (d *OpentelemetryTracingAccountRepositoryDecorator) CreateAccount(ctx context.Context, credential *credential.Entity, role entities.Role) (accountID *accountid.Entity, lerr logerr.Error) {

	var span trace.Span
	ctx, span = d.tracer.Start(ctx, "/CreateAccount")
	defer func() {
		defer span.End()
		if lerr == nil {
			return
		}
		if lerr.HasError() && d.recordErrors {
			span.RecordError(lerr.GetAPIError())
		}
	}()
	return d.base.CreateAccount(ctx, credential, role)
}

// GetTokenPayloadWithHashedPasswordByLogin implements repositories.AccountRepository
func (d *OpentelemetryTracingAccountRepositoryDecorator) GetTokenPayloadWithHashedPasswordByLogin(ctx context.Context, login string) (tokenPayload *tokenpayload.Entity, hashedPassword string, lerr logerr.Error) {

	var span trace.Span
	ctx, span = d.tracer.Start(ctx, "/GetTokenPayloadWithHashedPasswordByLogin")
	defer func() {
		defer span.End()
		if lerr == nil {
			return
		}
		if lerr.HasError() && d.recordErrors {
			span.RecordError(lerr.GetAPIError())
		}
	}()
	return d.base.GetTokenPayloadWithHashedPasswordByLogin(ctx, login)
}
