// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../core/pkg/decorators/templates/prometheus_metrics.go
// gowrap: http://github.com/hexdigest/gowrap

package decorators

//go:generate gowrap gen -p github.com/YFatMR/go_messenger/user_service/internal/services -i UserService -t ../../../../core/pkg/decorators/templates/prometheus_metrics.go -o prometheus_metrics.gen.go -v metricPrefix=service_request -l ""

import (
	"context"
	"time"

	"github.com/YFatMR/go_messenger/core/pkg/errors/logerr"
	"github.com/YFatMR/go_messenger/user_service/internal/entities/accountid"
	"github.com/YFatMR/go_messenger/user_service/internal/entities/user"
	"github.com/YFatMR/go_messenger/user_service/internal/entities/userid"
	"github.com/YFatMR/go_messenger/user_service/internal/services"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

type databaseOperatinTag string

const (
	okStatusTag    = "ok"
	errorStatusTag = "error"
)

// Prefixes:
// database_query: for database
// service_request: for seervices

// Naming rule: https://prometheus.io/docs/practices/naming/
var (
	databaseQueryDurationSeconds = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "service_request_duration_seconds",
		Buckets: []float64{0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 4},
		Help:    "Duration of one database query",
	}, []string{"status", "operation"})
	databaseQueryProcessedTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "service_request_processed_total",
		Help: "Count of query to database",
	}, []string{"status", "operation"})
	databaseQueryStartProcessTotal = promauto.NewCounter(prometheus.CounterOpts{
		Name: "service_request_start_process_total",
		Help: "Count of started queries",
	})
)

// PrometheusMetricsUserServiceDecorator implements services.UserService that is instrumented with custom zap logger
type PrometheusMetricsUserServiceDecorator struct {
	base services.UserService
}

// NewPrometheusMetricsUserServiceDecorator instruments an implementation of the services.UserService with simple logging
func NewPrometheusMetricsUserServiceDecorator(base services.UserService) *PrometheusMetricsUserServiceDecorator {
	if base == nil {
		panic("PrometheusMetricsUserServiceDecorator got empty base")
	}
	return &PrometheusMetricsUserServiceDecorator{
		base: base,
	}
}

// Create implements services.UserService
func (d *PrometheusMetricsUserServiceDecorator) Create(ctx context.Context, user *user.Entity, accountID *accountid.Entity) (userID *userid.Entity, lerr logerr.Error) {

	startTime := time.Now()
	databaseQueryStartProcessTotal.Inc()
	defer func() {
		functionDuration := time.Since(startTime).Seconds()
		statusTag := okStatusTag
		if lerr != nil && lerr.HasError() {
			statusTag = errorStatusTag
		}
		databaseQueryDurationSeconds.WithLabelValues(statusTag, "create").Observe(functionDuration)
		databaseQueryProcessedTotal.WithLabelValues(statusTag, "create").Inc()
	}()
	return d.base.Create(ctx, user, accountID)
}

// DeleteByID implements services.UserService
func (d *PrometheusMetricsUserServiceDecorator) DeleteByID(ctx context.Context, userID *userid.Entity) (lerr logerr.Error) {

	startTime := time.Now()
	databaseQueryStartProcessTotal.Inc()
	defer func() {
		functionDuration := time.Since(startTime).Seconds()
		statusTag := okStatusTag
		if lerr != nil && lerr.HasError() {
			statusTag = errorStatusTag
		}
		databaseQueryDurationSeconds.WithLabelValues(statusTag, "delete_by_id").Observe(functionDuration)
		databaseQueryProcessedTotal.WithLabelValues(statusTag, "delete_by_id").Inc()
	}()
	return d.base.DeleteByID(ctx, userID)
}

// GetByID implements services.UserService
func (d *PrometheusMetricsUserServiceDecorator) GetByID(ctx context.Context, userID *userid.Entity) (user *user.Entity, lerr logerr.Error) {

	startTime := time.Now()
	databaseQueryStartProcessTotal.Inc()
	defer func() {
		functionDuration := time.Since(startTime).Seconds()
		statusTag := okStatusTag
		if lerr != nil && lerr.HasError() {
			statusTag = errorStatusTag
		}
		databaseQueryDurationSeconds.WithLabelValues(statusTag, "get_by_id").Observe(functionDuration)
		databaseQueryProcessedTotal.WithLabelValues(statusTag, "get_by_id").Inc()
	}()
	return d.base.GetByID(ctx, userID)
}
