// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../core/pkg/decorators/templates/ulo_logger.go
// gowrap: http://github.com/hexdigest/gowrap

package decorators

//go:generate gowrap gen -p github.com/YFatMR/go_messenger/user_service/internal/controllers -i UserController -t ../../../../core/pkg/decorators/templates/ulo_logger.go -o ulo_logger.gen.go -l ""

import (
	"context"

	"github.com/YFatMR/go_messenger/core/pkg/loggers"
	"github.com/YFatMR/go_messenger/core/pkg/ulo"
	"github.com/YFatMR/go_messenger/protocol/pkg/proto"
	"github.com/YFatMR/go_messenger/user_service/internal/controllers"
	"go.uber.org/zap"
)

// LoggingUserControllerDecorator implements controllers.UserController that is instrumented with custom zap logger
type LoggingUserControllerDecorator struct {
	logger *loggers.OtelZapLoggerWithTraceID
	base   controllers.UserController
}

// NewLoggingUserControllerDecorator instruments an implementation of the controllers.UserController with simple logging
func NewLoggingUserControllerDecorator(base controllers.UserController, logger *loggers.OtelZapLoggerWithTraceID) *LoggingUserControllerDecorator {
	if base == nil {
		panic("LoggingUserControllerDecorator got empty base")
	}
	if logger == nil {
		panic("LoggingUserControllerDecorator got empty logger")
	}
	return &LoggingUserControllerDecorator{
		base:   base,
		logger: logger,
	}
}

// Create implements controllers.UserController
func (d *LoggingUserControllerDecorator) Create(ctx context.Context, request *proto.CreateUserDataRequest) (userID *proto.UserID, logstash ulo.LogStash, err error) {
	d.logger.DebugContextNoExport(ctx, "LoggingUserControllerDecorator: calling Create")
	defer func() {
		d.logger.LogContextNoExportULO(ctx, logstash)
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.DebugContextNoExport(ctx, "LoggingUserControllerDecorator: Create finished")
	}()
	return d.base.Create(ctx, request)
}

// DeleteByID implements controllers.UserController
func (d *LoggingUserControllerDecorator) DeleteByID(ctx context.Context, request *proto.UserID) (void *proto.Void, logstash ulo.LogStash, err error) {
	d.logger.DebugContextNoExport(ctx, "LoggingUserControllerDecorator: calling DeleteByID")
	defer func() {
		d.logger.LogContextNoExportULO(ctx, logstash)
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.DebugContextNoExport(ctx, "LoggingUserControllerDecorator: DeleteByID finished")
	}()
	return d.base.DeleteByID(ctx, request)
}

// GetByID implements controllers.UserController
func (d *LoggingUserControllerDecorator) GetByID(ctx context.Context, request *proto.UserID) (userData *proto.UserData, logstash ulo.LogStash, err error) {
	d.logger.DebugContextNoExport(ctx, "LoggingUserControllerDecorator: calling GetByID")
	defer func() {
		d.logger.LogContextNoExportULO(ctx, logstash)
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.DebugContextNoExport(ctx, "LoggingUserControllerDecorator: GetByID finished")
	}()
	return d.base.GetByID(ctx, request)
}

// Ping implements controllers.UserController
func (d *LoggingUserControllerDecorator) Ping(ctx context.Context, request *proto.Void) (pong *proto.Pong, logstash ulo.LogStash, err error) {
	d.logger.DebugContextNoExport(ctx, "LoggingUserControllerDecorator: calling Ping")
	defer func() {
		d.logger.LogContextNoExportULO(ctx, logstash)
		if err != nil {
			d.logger.ErrorContext(ctx, "", zap.NamedError("public api error", err))
		}
		d.logger.DebugContextNoExport(ctx, "LoggingUserControllerDecorator: Ping finished")
	}()
	return d.base.Ping(ctx, request)
}
