name: pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: Show go version
        run: echo $GOPATH && go version
