name: pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update and upgrade ubuntu packages
        run: sudo apt-get update && apt-get -y upgrade
      - name: Setup go environment
        run: sudo wget https://go.dev/dl/go1.19.linux-amd64.tar.gz && tar -xvf go1.19.linux-amd64.tar.gz && sudo mv go /usr/local
      - name: Setup go environment
        run: export GOROOT=/usr/local/go && export GOPATH=$HOME/messenger && export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
      - name: Show go version
        run: go version