// Code generated by gowrap. DO NOT EDIT.
// template: ../../core/pkg/decorators/templates/opentelemetry_tracing.template.go
// gowrap: http://github.com/hexdigest/gowrap

package decorator

//go:generate gowrap gen -p github.com/YFatMR/go_messenger/sandbox_service/apientity -i SandboxRepository -t ../../core/pkg/decorators/templates/opentelemetry_tracing.template.go -o sandbox_repository_opentelemetry_tracing.gen.go -l ""

import (
	"context"

	"github.com/YFatMR/go_messenger/sandbox_service/apientity"
	"github.com/YFatMR/go_messenger/sandbox_service/entity"
	"go.opentelemetry.io/otel/trace"
)

// OpentelemetryTracingSandboxRepositoryDecorator implements apientity.SandboxRepository that is instrumented with custom zap logger
type OpentelemetryTracingSandboxRepositoryDecorator struct {
	base         apientity.SandboxRepository
	tracer       trace.Tracer
	recordErrors bool
}

// NewOpentelemetryTracingSandboxRepositoryDecorator instruments an implementation of the apientity.SandboxRepository with simple logging
func NewOpentelemetryTracingSandboxRepositoryDecorator(base apientity.SandboxRepository, tracer trace.Tracer, recordErrors bool) *OpentelemetryTracingSandboxRepositoryDecorator {
	if base == nil {
		panic("OpentelemetryTracingSandboxRepositoryDecorator got empty base")
	}
	if tracer == nil {
		panic("OpentelemetryTracingSandboxRepositoryDecorator got empty tracer")
	}
	return &OpentelemetryTracingSandboxRepositoryDecorator{
		base:         base,
		tracer:       tracer,
		recordErrors: recordErrors,
	}
}

// CreateProgram implements apientity.SandboxRepository
func (d *OpentelemetryTracingSandboxRepositoryDecorator) CreateProgram(ctx context.Context, program *entity.ProgramSource) (programID *entity.ProgramID, err error) {

	var span trace.Span
	ctx, span = d.tracer.Start(ctx, "/CreateProgram")
	defer func() {
		if err != nil && d.recordErrors {
			span.RecordError(err)
		}
		span.End()
	}()
	return d.base.CreateProgram(ctx, program)
}

// GetProgramByID implements apientity.SandboxRepository
func (d *OpentelemetryTracingSandboxRepositoryDecorator) GetProgramByID(ctx context.Context, programID *entity.ProgramID) (program *entity.Program, err error) {

	var span trace.Span
	ctx, span = d.tracer.Start(ctx, "/GetProgramByID")
	defer func() {
		if err != nil && d.recordErrors {
			span.RecordError(err)
		}
		span.End()
	}()
	return d.base.GetProgramByID(ctx, programID)
}

// UpdateCodeRunnerOutput implements apientity.SandboxRepository
func (d *OpentelemetryTracingSandboxRepositoryDecorator) UpdateCodeRunnerOutput(ctx context.Context, programID *entity.ProgramID, newOutput *entity.ProgramOutput) (err error) {

	var span trace.Span
	ctx, span = d.tracer.Start(ctx, "/UpdateCodeRunnerOutput")
	defer func() {
		if err != nil && d.recordErrors {
			span.RecordError(err)
		}
		span.End()
	}()
	return d.base.UpdateCodeRunnerOutput(ctx, programID, newOutput)
}

// UpdateLinterOutput implements apientity.SandboxRepository
func (d *OpentelemetryTracingSandboxRepositoryDecorator) UpdateLinterOutput(ctx context.Context, programID *entity.ProgramID, newOutput *entity.ProgramOutput) (err error) {

	var span trace.Span
	ctx, span = d.tracer.Start(ctx, "/UpdateLinterOutput")
	defer func() {
		if err != nil && d.recordErrors {
			span.RecordError(err)
		}
		span.End()
	}()
	return d.base.UpdateLinterOutput(ctx, programID, newOutput)
}

// UpdateProgramSource implements apientity.SandboxRepository
func (d *OpentelemetryTracingSandboxRepositoryDecorator) UpdateProgramSource(ctx context.Context, programID *entity.ProgramID, programSource *entity.ProgramSource) (err error) {

	var span trace.Span
	ctx, span = d.tracer.Start(ctx, "/UpdateProgramSource")
	defer func() {
		if err != nil && d.recordErrors {
			span.RecordError(err)
		}
		span.End()
	}()
	return d.base.UpdateProgramSource(ctx, programID, programSource)
}
